### ISSUE TITLE
get_historical data 

### ISSUE THREAD

**Issue by offwinter** [ropensci/bomrang#79] opened 2018-07-17 06:10 UTC
Hi, I am new to R. When I try to repeat the sample `Canberra_mintemps <- get_historical(latlon = c(-35.2809, 149.1300),type = "min")`

It gives me the error like this: 

> Closest station: 070351 (CANBERRA AIRPORT)
trying URL 'http://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_display_type=dailyZippedDataFile&p_stn_num=070351&p_c=-989916801&p_nccObsCode=123'
Content type 'application/zip' length 19891 bytes (19 KB)
downloaded 19 KB

> Data  saved as 
Error in file(file, "rt") : invalid 'description' argument
In addition: Warning message:
In utils::unzip(tmp, exdir = dirname(tmp)) : zip file is corrupt

Is there anything I can do to fix it? Thanks in advance.

**Comment by jonocarroll** [comment] 2018-07-17 06:20
Cheers, I'll  look into this. It's a fairly new function so some things can still go wrong occasionally.

**Comment by adamhsparks** [comment] 2018-07-18 08:30
Duplicate of https://github.com/ropensci/bomrang/issues/75

**Comment by adamhsparks** [comment] 2018-07-18 08:32
Meant to mark as duplicate of this: https://github.com/ropensci/bomrang/issues/77

**Comment by adamhsparks** [comment] 2018-07-19 10:39
This fix is available from CRAN just an hor ago now.

-- 
Adam H Sparks

**Closed** 2018-07-19 11:01 UTC
